### ISSUE TITLE
PCA协议可能需要更新

### ISSUE THREAD

**Issue by bbz-233** [LeavesMC/Leaves#145]
### 服务端版本 LeavesMC Version

git-Leaves-"3f2d80d" (MC: 1.20.2)

### 预期的行为 Expected behavior

在客户端安装了Masa Gadget并开启了自动同步实体数据，服务端Leaves.yml启用了PCA协议(OPS_AND_SELF)且并未安装Via类插件的情况下，能同步所有实体的数据

### 观测到的实际行为 Observed/Actual behavior

在客户端安装了Masa Gadget 3.2.331+61c3583-stable并开启了自动同步实体数据，服务端Leaves.yml启用了PCA协议(OPS_AND_SELF)且未安装Via类插件的情况下，实体的数据并没有同步到客户端上(开启渲染村民交易补货冷却、渲染村民交易的第一本附魔书、渲染村民绑定床、渲染村民绑定工作方块、渲染僵尸村民转换时间、容器预览时同步数据后这些功能都无法正常工作)
并在客户端Masa Gadget配置界面开启debug模式并点击同步所有实体信息时,不会弹出任何带"update entity!"的调试信息

### 复现步骤 Steps/models to reproduce

1 从旧版本升级服务器核心)

服务端配置文件开启PCA协议支持,卸载Via类(比如ViaVerison)插件
客户端安装Masa Gadget(我使用的3.2.331+61c3583-stable)、Malilib(1.20.2-0.17.0)、魔法类库(0.7.387+c02a0de-stable)
并开启自动实体数据

![image](https://github.com/LeavesMC/Leaves/assets/92072976/d24557e4-4f38-4068-b82d-e3678e138a68)

![image](https://github.com/LeavesMC/Leaves/assets/92072976/7e8868be-79aa-4b3d-a22e-cb882260865e)

2 重新下载服务器核心并搭建)

下载Leaves核心[git-Leaves-"3f2d80d" (MC: 1.20.2)]
启动服务器,然后编辑EULA文件(第一次启动)
服务端配置文件开启PCA协议支持
启动服务器

### 插件与数据包列表。 Plugin and Datapack List.

1)
![image](https://github.com/LeavesMC/Leaves/assets/92072976/e51dd046-70f4-4c73-8ce6-f94b4279e77e)

2)
无插件无数据包
![image](https://github.com/LeavesMC/Leaves/assets/92072976/8bc848e8-bddf-4f92-844f-6edb75522d5b)

这些数据包和插件在使用 git-Leaves-"3639506" (MC: 1.20.1)加载时并不会出现上述问题

**Comment by s-yh-china** [comment]
我并没有观察到MasaGadget那边有变动
可能你需要把MasaGadget的debug打开然后看看日志里有没有输出update entity!这样的信息
~这几个月太累，暂时没时间测试~

**Comment by bbz-233** [comment]
[八宝粥的数据包.zip](https://github.com/LeavesMC/Leaves/files/13056094/default.zip)
更多进度 https://wwt.lanzoub.com/ioBuy09ugyni
彩虹像素(材质+数据) https://wwcf.lanzout.com/iwANv0zyimwh
Terralith https://www.curseforge.com/minecraft/mc-mods/terralith (v2.4.0)
Structory https://www.curseforge.com/minecraft/mc-mods/structory (v1.3.2)
Towns and Towers https://www.planetminecraft.com/data-pack/towns-amp-towers-structure-overhaul/
Villages Overhauled https://www.planetminecraft.com/data-pack/villages-overhauled/

**Comment by bbz-233** [comment]
[00:10:04] [Render thread/DEBUG]: syncEntity: 74
[00:10:04] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:04] [Render thread/DEBUG]: syncEntity: 75
[00:10:04] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:04] [Render thread/DEBUG]: syncEntity: 78
[00:10:04] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:04] [Render thread/DEBUG]: syncEntity: 79
[00:10:04] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:04] [Render thread/DEBUG]: syncEntity: 121
[00:10:04] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:04] [Render thread/DEBUG]: syncEntity: 122
[00:10:04] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:04] [Render thread/DEBUG]: syncEntity: 125
[00:10:04] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:04] [Render thread/DEBUG]: syncEntity: 126
[00:10:04] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:04] [Render thread/DEBUG]: syncEntity: 127
[00:10:04] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:04] [Render thread/DEBUG]: syncEntity: 129
[00:10:04] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:04] [Render thread/DEBUG]: syncEntity: 147
[00:10:04] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:04] [Render thread/INFO]: Stopping worker threads
[00:10:04] [Netty Client IO #15/DEBUG]: update entity!
[00:10:04] [Render thread/INFO]: Started 10 worker threads
[00:10:04] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:04] [Netty Client IO #15/DEBUG]: update entity!
[00:10:04] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:04] [Netty Client IO #15/DEBUG]: update entity!
[00:10:04] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:04] [Netty Client IO #15/DEBUG]: update entity!
[00:10:04] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:04] [Netty Client IO #15/DEBUG]: update entity!
[00:10:04] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:04] [Netty Client IO #15/DEBUG]: update entity!
[00:10:04] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:04] [Netty Client IO #15/DEBUG]: update entity!
[00:10:04] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:04] [Netty Client IO #15/DEBUG]: update entity!
[00:10:04] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:04] [Netty Client IO #15/DEBUG]: update entity!
[00:10:04] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:04] [Netty Client IO #15/DEBUG]: update entity!
[00:10:04] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:04] [Netty Client IO #15/DEBUG]: update entity!
[00:10:04] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:04] [Render thread/WARN]: Program link log for sodium:chunk_shader_for_gbuffers_water: Fragment info
-------------
0(1018) : warning C7050: "smoothnessD" might be used before being initialized
0(1018) : warning C7050: "materialMaskPh" might be used before being initialized

[00:10:12] [Render thread/DEBUG]: syncEntity: 79
[00:10:12] [Netty Client IO #15/DEBUG]: update entity!
[00:10:12] [Netty Client IO #15/ERROR]: Not a map: END
[00:10:14] [Render thread/DEBUG]: cancelSyncEntity.
[00:10:16] [Render thread/INFO]: pcaSyncProtocol onDisconnect.
[00:10:16] [Render thread/INFO]: Minimap session finalized.
[00:10:16] [Render thread/INFO]: Finalizing world map session...
[00:10:16] [Thread-21/INFO]: World map force-cleaned!
[00:10:16] [Render thread/INFO]: World map session finalized.
[00:10:16] [Render thread/INFO]: Stopping worker threads
[00:10:16] [Render thread/INFO]: Adding auth button to the multiplayer screen
[00:10:21] [Render thread/INFO]: pcaSyncProtocol onDisconnect.
[00:10:21] [Render thread/INFO]: Connecting to 127.0.0.2, 25565
[00:10:26] [Render thread/WARN]: Unknown custom packet payload: syncmatica:register_version
有写到"update entity!"的大概是这样的片段，点击同步实体数据时聊天框不会弹出完成同步的消息

**Comment by bbz-233** [comment]
今天又试了下，直接没有"update entity!"的字样了

**Comment by s-yh-china** [comment]
已修复，需要测试

**Comment by bbz-233** [comment]
有构建版本吗，我想帮忙试下

**Comment by bbz-233** [comment]
我这就下下来试下

**Comment by bbz-233** [comment]
好像仍然没有效果
而且在进入Leaves核心的服务器后找不到update entity!的字样
![image](https://github.com/LeavesMC/Leaves/assets/92072976/6754dc02-b446-4f04-9306-1c6d07b49fdf)
![image](https://github.com/LeavesMC/Leaves/assets/92072976/1e2d1a1e-5d51-4b7b-89e4-b0525a59e57f)

**Comment by s-yh-china** [comment]
啊? 我这边是完全没有问题的 给下leaves.yml?

**Comment by bbz-233** [comment]
```
# Configuration file for Leaves.

settings:
  performance:
    remove:
      get-nearby-players-streams: true
      tick-guard-lambda: true
      inventory-contains-iterators: true
      range-check-streams-and-iterators: true
      damage-lambda: true
    skip-entity-move-if-movement-is-zero: true
    reduce-entity-fluid-lookup: true
    strip-raytracing-for-entity: true
    check-frozen-ticks-before-landing-block: true
    enable-suffocation-optimization: true
    use-fast-item-merge-raytracing: true
    cache-CubeVoxelShape-shape-array: true
    optimize-sun-burn-tick: true
    cache-ignite-odds: true
    skip-negligible-planar-movement-multiplication: true
    dont-trigger-lootable-refresh-for-non-player: true
    cache-climb-check: true
    improve-fluid-direction-caching: true
    optimized-CubePointRange: true
    inactive-goal-selector-disable: false
    fix:
      fix-paper-9372: true
      fix-paper-6045: true
    skip-unnecessary-mob-spawning-computations: true
    use-optimized-collection: true
    optimize-chunk-ticking: true
    async-mob-spawning: false
    dont-send-useless-entity-packets: true
    optimize-entity-coordinate-key: true
    check-spooky-season-once-an-hour: false
    optimize-world-generation-and-block-access: true
    reduce-entity-allocations: true
    skip-poi-find-in-vehicle: true
    entity-target-find-optimization: true
    biome-temperatures-use-aging-cache: true
    simpler-vanilla-shapeless-recipes: true
    reduce-chuck-load-and-lookup: true
    optimized-dragon-respawn: false
    faster-chunk-serialization: true
    use-more-thread-unsafe-random: true
    async-pathfinding: false
    async-entity-tracker: false
    optimize-noise-generation: false
    cache-ominous-banner-item: true
    skip-cloning-advancement-criteria: false
    cache-BlockStatePairKey-hash: true
    cache-world-generator-sea-level: true
    fix-villagers-dont-release-memory: true
    store-mob-counts-in-array: true
    skip-secondary-POI-sensor-if-absent: true
  misc:
    server-mod-name: "Paper"
    disable-method-profiler: true
    server-lang: zh_cn
    no-chat-sign: true
    extra-yggdrasil-service:
      enable: false
      login-protect: false
      urls:
      - https://url.with.authlib-injector-yggdrasil
    dont-respond-ping-before-start-fully: true
    bstats-privacy-mode: false
    auto-update:
      enable: true
      time:
      - '2:00'
      - '5:30'
  modify:
    disable-moved-wrongly-threshold: false
    minecraft-old:
      armor-stand-cant-kill-by-mob-projectile: false
      cce-update-suppression: false
      villager-infinite-discounts: false
      zero-tick-plants: true
      instant-block-updater-reintroduced: false
      redstone-wire-dont-connect-if-on-trapdoor: false
      loot-world-random: false
      mending-compatibility-infinity: false
      shears-in-dispenser-can-zero-amount: false
    force-void-trade: false
    tick-command: false
    hopper-counter: false
    spider-jockeys-drop-gapples: -1.0
    flatten-triangular-distribution: false
    mc-technical-survival-mode: true
    use-vanilla-random: false
    creative-no-clip: false
    return-nether-portal-fix: false
    container-passthrough: true
    no-feather-falling-trample: false
    fix-update-suppression-crash: true
    budding-amethyst-can-push-by-piston: false
    snowball-and-egg-can-knockback-player: true
    redstone-shears-wrench: true
    spectator-dont-get-advancement: true
    avoid-anvil-too-expensive: true
    despawn-enderman-with-block: false
    no-block-update-command: false
    disable-check-out-of-order-command: false
    player-operation-limiter: false
    stackable-shulker-boxes: 'false'
    disable-distance-check-for-use-item: false
    shared-villager-discounts: false
    ignore-lc: false
    bedrock-break-list: false
    raider-die-skip-self-raid-check: false
    lava-riptide: false
    disable-packet-limit: false
    bow-infinity-fix: true
    shave-snow-layers: true
    renewable-elytra: -1.0
    fakeplayer:
      spawn-phantom: false
      enable: true
      unable-fakeplayer-names:
      - player-name
      limit: 10
      prefix: ''
      suffix: ''
      always-send-data: true
      resident-fakeplayer: true
      open-fakeplayer-inventory: true
      skip-sleep-check: true
    elytra-aeronautics:
      no-chunk-load: true
      no-chunk-height: 64.0
      no-chunk-speed: 40.0
      message: true
      message-start: 飞行速度过快,将停止区块加载
      message-end: 飞行速度减缓,将恢复区块加载
    stick-change-armorstand-arm-status: true
  protocol:
    servux-protocol: true
    pca-sync-protocol: true
    alternative-block-placement: LITEMATICA
    leaves-carpet-support: true
    pca-sync-player-entity: OPS_AND_SELF
    jade-protocol: true
    bbor-protocol: true
    xaero-map-protocol: false
    xaero-map-server-id: -2094485729
    bladeren:
      protocol: true
      mspt-sync-tick-interval: 20
      mspt-sync-protocol: false
    appleskin-protocol: true
    syncmatica:
      enable: true
      quota: true
      quota-limit: 40000000
config-version: 5
world-settings:
  default: {}
  world: {}
  world_nether: {}
  world_the_end: {}

```
