### ISSUE TITLE
Leaves 假人的权限组未在文档中描述

### ISSUE THREAD

**Issue by ENTNEAZ** [LeavesMC/Leaves#156]
### 描述你希望添加的功能。 Describe the feature you'd like.

`/bot` 命令似乎是op命令 是否可以在文档中增加有关`/bot`命令权限/权限组的详细描述

方便将权限授权给玩家

例如：

```yaml
coreprotect.inspect:
  description: "co i"
  default: op
bukkit.command.tps:
  description: "tps"
  default: op
```

### 其他 Other

测试版本:1.20
