### ISSUE TITLE
原版体验

### ISSUE THREAD

**Issue by LittleChest** [LeavesMC/Leaves#373]
### 描述你希望添加的功能。 Describe the feature you'd like.

新增 `vanilla-experience` 配置项 用于强制覆盖 [这里](https://docs.papermc.io/paper/vanilla) 的所有内容

原 `mc-technical-survival-mode` 配置项可用于在 `vanilla-experience` 基础上强制覆盖不那么原版但对生电有帮助的配置 ~~（目前好像没有 可删掉）~~

**Comment by MC-XiaoHei** [comment]
scoreboards.use-vanilla-world-scoreboard-name-coloring: true
这个也有必要吗，似乎会导致一些问题，它大概不会影响生电吧

**Comment by LittleChest** [comment]
> scoreboards.use-vanilla-world-scoreboard-name-coloring: true 这个也有必要吗，似乎会导致一些问题，它大概不会影响生电吧

这个有什么问题🤔

**Comment by MC-XiaoHei** [comment]
https://github.com/LeavesMC/Leaves/issues/367

**Comment by MC-XiaoHei** [comment]
讲实话我确实不是很喜欢technical mode这个强制覆盖（）
就像 #367 那样一但不需要某个配置就需要手动改其他的所有配置

**Comment by LittleChest** [comment]
> #367

这是插件问题 插件没有设置对应的计分版颜色 设置一个fallback就行了

**Comment by Lumine1909** [comment]
> 讲实话我确实不是很喜欢technical mode这个强制覆盖（） 就像 #367 那样一但不需要某个配置就需要手动改其他的所有配置

加个自定义的配置包呢？
这样既方便配置也能避免这种问题

例如
```yaml
fix:
  xxxxx:
protocol:
  xxxxxx:

pack:
  mc-tech-xxx:
    - xxx
    - xxx
    - xxx
  vanilla-xxx:
    - xxx
    - xxx

```
